- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      fra: "{{ lookup('airport', 'fra') }}"
      nop: "no4"
  tasks:
  - debug:
        msg: "FRA is {{ fra.name }} in {{ fra.city }}"

  - debug:
        msg: "Barcelona is at {{ lookup('airport', 'bcn').osm }}"

  - debug:
        var: fra

  - debug:
        msg: "The airport code {{ nop }} is {{ lookup('airport', nop) }}"
    ignore_errors: true
